### ISSUE TITLE
Promise interface

### ISSUE THREAD

**Issue by bsonntag** [yahoo/badge-up#3]
Do you have any plans to add a promise interface?

I would be nice to use `badge-up` like:

``` js
badge('batman', 'component', badge.colors.green)
  .then(function(svg) {
    // ...
  });
```

**Comment by stjohnjohnson** [comment]
Great question. I'd want to support callbacks and promises together as I know many people are still callback-centric.

I just found [a library](https://www.npmjs.com/package/polygoat) that claims to support both without forcing a promise implementation.  So I'll be looking into that.

In the meantime, most promise libraries have converters (like Bluebird):

```js
var Promise = require('bluebird');
var badge = Promise.promisify(require('badge-up'));

badge('batman', 'component', badge.colors.green).
    then(function (svg) { 
        console.log(svg);  // <svg xmlns="http://www.w3.org/2000/svg" wi...
    });
```

**Comment by brettz9** [comment]
With #12 merged, I think this can be closed as the basic request was I think implemented.

**Comment by bsonntag** [comment]
Thanks @brettz9
